import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Scroll from "@/components/Scroll";
import Footer from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "E-Cell KIIT",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased`}
      >
        <Scroll />
        <main className="relative w-full flex flex-col items-center">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
