import type { Metadata } from "next";
import { Poppins, Satisfy } from "next/font/google";
import "./globals.css";
import Scroll from "@/components/Scroll";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { usePathname } from "next/navigation";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const satisfy = Satisfy({
  variable: "--font-satisfy",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "E-Cell KIIT",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = typeof window !== "undefined" ? window.location.pathname : "";
  const is404 = pathname === "/not-found";
  return (
    <html lang="en">
      <body
        className={` ${poppins.variable} antialiased`}
      >
        <Scroll />
        <main className="relative w-full flex flex-col items-center overflow-hidden">
          {children}
          {!is404 && <Footer />}
        </main>
      </body>
    </html>
  );
}
